spring:
  config:
    activate:
      on-profile: qa

  server:
    port: 8080

  datasource:
    url: jdbc:postgresql://localhost:5432/keralavotes
    username: keralavotes
    password: keralavotes
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: QAHikariPool
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 2400000
      connection-timeout: 100000
      validation-timeout: 50000
      keepalive-time: 1000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate.format_sql: true
  mongodb:
    uri: mongodb://appuser:apppassword@localhost:27017/keralavotes?authSource=keralavotes
    database: keralavotes
    authentication-database: keralavotes

#  web:
#    cors:
#      allowed-origins: "http://localhost:3333"
#      allowed-methods: "*"
#      allowed-headers: "*"
#      allow-credentials: true

logging:
  level:
    root: INFO
    com.keralavotes: DEBUG
  file:
    name: logs/keralavotes.log