spring:
  application:
    name: TrackerService

  profiles:
    default: dev

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    root: INFO
    com.keralavotes: DEBUG
  file:
    name: logs/keralavotes.log