spring:
  application:
    name: TrackerService

  profiles:
    default: dev

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    hikari:
      maximum-pool-size: 20
      auto-commit: false

logging:
  level:
    root: INFO
    com.keralavotes: DEBUG
  file:
    name: logs/keralavotes.log