spring:
  config:
    activate:
      on-profile: prod

  server:
    port: ${PORT:8080}

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require&tcpKeepAlive=true&loginTimeout=10&socketTimeout=30
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: NeonHikariPool
      maximum-pool-size: 5
      minimum-idle: 0
      idle-timeout: 30000
      max-lifetime: 240000
      connection-timeout: 10000
      validation-timeout: 5000
      keepalive-time: 0
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  mongodb:
    uri: mongodb://appuser:apppassword@localhost:27017/keralavotes?authSource=keralavotes
    database: keralavotes
    authentication-database: keralavotes

#  web:
#    cors:
#      allowed-origins: "http://localhost:3333, https://kerala-votes.vercel.app, https://keralaelects.onrender.com"
#      allowed-methods: "*"
#      allowed-headers: "*"
#      allow-credentials: true

logging:
  level:
    root: INFO
    com.keralavotes: DEBUG
  file:
    name: logs/keralavotes.log